

#ifndef _Included_com_ers_bluetones_SimpleWrap
#define _Included_com_ers_bluetones_SimpleWrap
#if PLATFORM_ANDROID/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "Holder.h"
#include "CPPRelay.h"
/* Header for class com_ers_bluetones_SimpleWrap */

#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_ers_bluetones_BlueService
	* Method:    initNative
	* Signature: (Ljava/lang/Class;)V
	*/
	JNIEXPORT void JNICALL Java_com_ers_bluetones_BlueService_initNative
		(JNIEnv *, jobject, jclass);

	JNIEXPORT void JNICALL Java_com_ers_bluetones_BlueService_syncData
		(JNIEnv *, jclass);
	/*
	* Class:     com_ers_bluetones_BlueService
	* Method:    initNative
	* Signature: (Ljava/lang/String;)V
	*/
	JNIEXPORT void JNICALL Java_com_ers_bluetones_BlueService_foundDevice
		(JNIEnv *, jobject, jstring, jstring);

	/*
	* Class:     com_ers_bluetones_SimpleWrap
	* Method:    receiveData
	* Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;)V
	*/
	JNIEXPORT void JNICALL Java_com_ers_bluetones_BlueService_receiveData
		(JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
#endif
